Tidy up & remove duplicate + dead links
chakra-ui/awesome-chakra-ui pull request #68
Opened 2022-07-30 10:35 UTC by mountainash

Just some general house-cleaning...

My "goal" was to remove the 3 broken Polygon links from the Showcase page at https://chakra-ui.com/community/showcase (the *Submit your project* link point to this repo) - but it doesn't appear like the Showcase is automatically generated from the content of this project. Maybe whichever maintainer to read this also has access to the Showcase source?

2022-09-22 06:46 UTC, nikolovlazar requested changes
Thanks for working on this @mountainash 🙌! I left you one comment about a deleted article that still exists, and I can also see there are some merge conflicts as well. Could you take care of that?

2022-09-22 06:46 UTC, nikolovlazar commented on README.md
> -- [Choosing the right component library for your design system: MUI vs Chakra](https://engineering.udacity.com/choosing-the-right-component-library-for-your-design-system-mui-vs-chakra-45c4c949d150)
This is not a dead link. The article exists.

2022-09-22 06:46 UTC, nikolovlazar commented on contributing.md
> -
Good catch!

2022-09-23 08:35 UTC, mountainash commented on README.md
> -- [Choosing the right component library for your design system: MUI vs Chakra](https://engineering.udacity.com/choosing-the-right-component-library-for-your-design-system-mui-vs-chakra-45c4c949d150)
Yes... but it's a duplicate of the same link two list-items above.

2022-09-23 09:03 UTC, mountainash commented
Hello @nikolovlazar I've made the requested changes and updated the branch from the upstream HEAD ready for merge, then updated all the new changes as well.

Do you know if this will fix the original intention of cleaning up the broken links on https://chakra-ui.com/community/showcase ?

2022-09-23 09:35 UTC, nikolovlazar commented on README.md
> -- [Choosing the right component library for your design system: MUI vs Chakra](https://engineering.udacity.com/choosing-the-right-component-library-for-your-design-system-mui-vs-chakra-45c4c949d150)
Ah, got it!

2022-09-23 09:35 UTC, nikolovlazar approved these changes
LGTM!

2022-09-23 09:35 UTC, merged

2022-09-23 09:35 UTC, nikolovlazar commented
@mountainash yes it will!

2022-09-23 10:40 UTC, mountainash commented
> yes it will!

Doesn't seem to have changed... might want to check out if any automatons are broken?

2022-09-23 10:48 UTC, nikolovlazar commented
@mountainash the `update sponsors, members, showcase and avatars` PR will pick it up tomorrow morning: https://github.com/chakra-ui/chakra-ui-docs/pull/1006

2022-09-23 16:21 UTC, nikolovlazar commented
Don't worry. That's the one we need. Here's the action if you want to see everything that's happening: https://github.com/chakra-ui/chakra-ui-docs/actions/runs/3109570238/jobs/5039893254